import { Context } from "effect";

import type { OrderRepository } from "./order.types";

export {
  createOrderId,
  createOrderIdEffect,
  createOrderLineItemId,
  createOrderLineItemIdEffect,
  createOrderTransactionId,
  createOrderTransactionIdEffect,
  ORDER_ID_PREFIX,
  ORDER_LINE_ITEM_ID_PREFIX,
  ORDER_TRANSACTION_ID_PREFIX,
  serializeOrderId,
  serializeOrderLineItemId,
  serializeOrderTransactionId,
  type OrderId,
  type OrderLineItemId,
  type OrderTransactionId,
} from "./order-id";
export {
  CreateOrderFromCheckoutInputSchema,
  CreateOrderLineItemInputSchema,
  OrderAddressSnapshotSchema,
  OrderAggregateApiSchema,
  OrderAggregateSchema,
  OrderApiListSchema,
  OrderApiRecordSchema,
  OrderCoordinationMetadataSchema,
  OrderCurrencyCodeSchema,
  OrderFulfillmentReferenceSchema,
  OrderIdentifierSchema,
  OrderIsoDateTimeStringSchema,
  OrderItemSnapshotSchema,
  OrderLineItemIdSchema,
  OrderLineItemSerializedIdSchema,
  OrderLineItemApiRecordSchema,
  OrderLineItemRecordSchema,
  OrderMetadataSchema,
  OrderNonNegativeIntegerSchema,
  OrderNullableIsoDateTimeStringSchema,
  OrderPaymentReferenceSchema,
  OrderPostPurchaseOperationApiRecordSchema,
  OrderPostPurchaseOperationRecordSchema,
  OrderPostPurchaseOperationTypeSchema,
  OrderRecordSchema,
  OrderSerializedIdSchema,
  OrderStateTransitionApiRecordSchema,
  OrderStateTransitionRecordSchema,
  OrderStatusSchema,
  OrderTotalsSnapshotSchema,
  OrderTransactionIdSchema,
  OrderTransactionSerializedIdSchema,
  OrderTransactionApiRecordSchema,
  OrderTransactionRecordSchema,
  RecordOrderTransactionInputSchema,
  OrderTransactionTypeSchema,
  OrderTrimmedStringSchema,
  TransitionOrderStatusInputSchema,
} from "./order.schema";
export {
  OrderInvalidIdentifier,
  OrderNotFound,
  OrderValidationFailure,
  type OrderExpectedError,
} from "./order.errors";
export type {
  CreateOrderFromCheckoutInput,
  CreateOrderLineItemInput,
  OrderAddressSnapshot,
  OrderAggregate,
  OrderAggregateApiRecord,
  OrderApiList,
  OrderApiRecord,
  OrderFulfillmentReference,
  OrderIdentifierInput,
  OrderItemSnapshot,
  OrderLineItemApiRecord,
  OrderLineItemRecord,
  OrderPaymentReference,
  OrderPostPurchaseOperationRecord,
  OrderRecord,
  OrderRepository,
  OrderStateTransitionRecord,
  OrderStatus,
  OrderTotalsSnapshot,
  OrderTransactionApiRecord,
  OrderTransactionRecord,
  OrderTransactionType,
  RecordOrderTransactionInput,
  TransitionOrderStatusInput,
} from "./order.types";

export const OrderRepositoryService = Context.Service<OrderRepository>(
  "@ecommerce/order/OrderRepository"
);
