export { inventoryAdminMetadata, inventoryAdminSurfaces } from "./admin";
export {
  AdjustInventoryInputSchema,
  CreateInventoryItemInputSchema,
  CreateStockLocationInputSchema,
  INVENTORY_ADJUSTMENT_EVENT_ID_PREFIX,
  INVENTORY_ITEM_ID_PREFIX,
  INVENTORY_LEVEL_ID_PREFIX,
  INVENTORY_RESERVATION_ID_PREFIX,
  InventoryAdjustmentEventApiRecordSchema,
  InventoryAdjustmentEventIdSchema,
  InventoryAdjustmentEventSerializedIdSchema,
  InventoryAdjustmentEventRecordSchema,
  InventoryAdjustmentReasonSchema,
  InventoryAvailabilityApiSchema,
  InventoryAvailabilityInputSchema,
  InventoryAvailabilitySchema,
  InventoryInsufficientStock,
  InventoryInvalidIdentifier,
  InventoryIsoDateTimeStringSchema,
  InventoryItemApiRecordSchema,
  InventoryItemIdSchema,
  InventoryItemSerializedIdSchema,
  InventoryItemNotFound,
  InventoryItemRecordSchema,
  InventoryLevelIdSchema,
  InventoryLevelApiRecordSchema,
  InventoryLevelSerializedIdSchema,
  InventoryLevelNotFound,
  InventoryLevelRecordSchema,
  InventoryMetadataSchema,
  InventoryPositiveQuantitySchema,
  InventoryQuantitySchema,
  InventoryRepositoryService,
  InventoryReservationApiRecordSchema,
  InventoryReservationIdSchema,
  InventoryReservationSerializedIdSchema,
  InventoryReservationRecordSchema,
  InventoryReservationStatusSchema,
  InventoryTrimmedStringSchema,
  ReservationResultApiSchema,
  ReservationResultSchema,
  ReserveInventoryInputSchema,
  STOCK_LOCATION_ID_PREFIX,
  SetInventoryLevelInputSchema,
  StockLocationIdSchema,
  StockLocationApiRecordSchema,
  StockLocationSerializedIdSchema,
  StockLocationNotFound,
  StockLocationRecordSchema,
  InventoryValidationFailure,
  createInventoryAdjustmentEventIdEffect,
  createInventoryAdjustmentEventId,
  createInventoryItemIdEffect,
  createInventoryItemId,
  createInventoryLevelIdEffect,
  createInventoryLevelId,
  createInventoryReservationIdEffect,
  createInventoryReservationId,
  createStockLocationIdEffect,
  createStockLocationId,
  serializeInventoryAdjustmentEventId,
  serializeInventoryItemId,
  serializeInventoryLevelId,
  serializeInventoryReservationId,
  serializeStockLocationId,
} from "./domain";
export type {
  AdjustInventoryInput,
  CreateInventoryItemInput,
  CreateStockLocationInput,
  InventoryAdjustmentEventApiRecord,
  InventoryAdjustmentEventId,
  InventoryAdjustmentEventRecord,
  InventoryAdjustmentReason,
  InventoryAvailability,
  InventoryAvailabilityApiRecord,
  InventoryAvailabilityInput,
  InventoryExpectedError,
  InventoryItemApiRecord,
  InventoryItemId,
  InventoryItemRecord,
  InventoryLevelApiRecord,
  InventoryLevelId,
  InventoryLevelRecord,
  InventoryRepository,
  InventoryReservationApiRecord,
  InventoryReservationId,
  InventoryReservationRecord,
  InventoryReservationSaveResult,
  InventoryReservationStatus,
  ReserveInventoryInput,
  ReservationResult,
  ReservationResultApiRecord,
  SetInventoryLevelInput,
  StockLocationApiRecord,
  StockLocationId,
  StockLocationRecord,
} from "./domain";
export { inventoryExtensionPoints, inventoryModule } from "./module";
export { inventoryPermissionList, inventoryPermissions } from "./permissions";
export {
  InMemoryInventoryRepository,
  createInMemoryInventoryRepositoryLayer,
  createInMemoryInventoryRepository,
  createResettableInMemoryInventoryRepository,
  defaultInventoryRepository,
  type ResettableInventoryRepository,
} from "./repositories";
export {
  INVENTORY_ADJUSTED_EVENT,
  INVENTORY_RESERVED_EVENT,
  InventoryService,
  createInventoryRepositoryLayer,
  createInventoryService,
  createInventoryServiceFromDependenciesLayer,
  createInventoryServiceLayer,
  defaultInventoryService,
  type CreateInventoryServiceOptions,
  type InventoryAdjustedEventPayload,
  type InventoryReservedEventPayload,
  type InventoryServiceShape,
} from "./services";
export { createTestInventoryService } from "./testing";
