export {
  createD1InventoryRepository,
  type CreateD1InventoryRepositoryOptions,
  type InventoryD1Database,
} from "./adapters";
export { inventoryAdminMetadata, inventoryAdminSurfaces } from "./admin";
export { inventoryContractRouter } from "./contracts";
export {
  AdjustInventoryInputSchema,
  CreateInventoryItemInputSchema,
  CreateStockLocationInputSchema,
  INVENTORY_ADJUSTMENT_EVENT_ID_PREFIX,
  INVENTORY_ITEM_ID_PREFIX,
  INVENTORY_LEVEL_ID_PREFIX,
  INVENTORY_RESERVATION_ID_PREFIX,
  InventoryAdjustmentEventApiRecordSchema,
  InventoryAdjustmentEventRecordSchema,
  InventoryAdjustmentReasonSchema,
  InventoryAvailabilityApiSchema,
  InventoryAvailabilityInputSchema,
  InventoryAvailabilitySchema,
  InventoryItemApiRecordSchema,
  InventoryItemRecordSchema,
  InventoryLevelApiRecordSchema,
  InventoryLevelRecordSchema,
  InventoryReservationApiRecordSchema,
  InventoryReservationRecordSchema,
  InventoryReservationStatusSchema,
  ReservationResultApiSchema,
  ReservationResultSchema,
  ReserveInventoryInputSchema,
  STOCK_LOCATION_ID_PREFIX,
  SetInventoryLevelInputSchema,
  StockLocationApiRecordSchema,
  StockLocationRecordSchema,
  createInventoryAdjustmentEventId,
  createInventoryItemId,
  createInventoryLevelId,
  createInventoryReservationId,
  createStockLocationId,
  inventoryMigration,
  inventorySchema,
  serializeInventoryAdjustmentEventId,
  serializeInventoryItemId,
  serializeInventoryLevelId,
  serializeInventoryReservationId,
  serializeStockLocationId,
} from "./domain";
export type {
  AdjustInventoryInput,
  CreateInventoryItemInput,
  CreateStockLocationInput,
  InventoryAdjustmentEventApiRecord,
  InventoryAdjustmentEventId,
  InventoryAdjustmentEventRecord,
  InventoryAdjustmentReason,
  InventoryAvailability,
  InventoryAvailabilityApiRecord,
  InventoryAvailabilityInput,
  InventoryDatabase,
  InventoryDatabaseSchema,
  InventoryItemApiRecord,
  InventoryItemId,
  InventoryItemRecord,
  InventoryLevelApiRecord,
  InventoryLevelId,
  InventoryLevelRecord,
  InventoryRepository,
  InventoryReservationApiRecord,
  InventoryReservationId,
  InventoryReservationRecord,
  InventoryReservationStatus,
  ReserveInventoryInput,
  ReservationResult,
  ReservationResultApiRecord,
  SetInventoryLevelInput,
  StockLocationApiRecord,
  StockLocationId,
  StockLocationRecord,
} from "./domain";
export { inventoryExtensionPoints, inventoryModule } from "./module";
export { inventoryPermissionList, inventoryPermissions } from "./permissions";
export {
  InMemoryInventoryRepository,
  createInMemoryInventoryRepository,
  createResettableInMemoryInventoryRepository,
  defaultInventoryRepository,
  type ResettableInventoryRepository,
} from "./repositories";
export {
  createInventoryRouteFragment,
  inventoryApiFragment,
  inventoryRouter,
  type CreateInventoryRouteFragmentOptions,
  type InventoryModuleContext,
} from "./router";
export {
  INVENTORY_ADJUSTED_EVENT,
  INVENTORY_RESERVED_EVENT,
  InventoryService,
  createInventoryService,
  createInventoryServiceLayer,
  defaultInventoryService,
  type CreateInventoryServiceOptions,
  type InventoryAdjustedEventPayload,
  type InventoryReservedEventPayload,
  type InventoryServiceShape,
} from "./services";
export { createTestInventoryService } from "./testing";
