export {
  CUSTOMER_AUTH_LINKED_EVENT,
  CUSTOMER_CREATED_EVENT,
  CUSTOMER_UPDATED_EVENT,
  CustomerService,
  createCustomerRepositoryLayer,
  createCustomerServiceFromDependenciesLayer,
  createCustomerService,
  createCustomerServiceLayer,
  defaultCustomerService,
  type CreateCustomerServiceOptions,
  type CustomerAuthLinkedEventPayload,
  type CustomerChangedEventPayload,
  type CustomerServiceFailure,
  type CustomerServiceShape,
} from "./customer.service";
