export { customerAdminMetadata, customerAdminSurfaces } from "./admin";
export {
  CUSTOMER_ADDRESS_ID_PREFIX,
  CUSTOMER_GROUP_ID_PREFIX,
  CUSTOMER_ID_PREFIX,
  CreateCustomerAddressInputSchema,
  CreateCustomerGroupInputSchema,
  CreateCustomerInputSchema,
  CustomerAddressIdSchema,
  CustomerAddressKindSchema,
  CustomerAddressSchema,
  CustomerApiAddressSchema,
  CustomerApiGroupSchema,
  CustomerApiListSchema,
  CustomerApiProfileSchema,
  CustomerAuthUserConflict,
  CustomerEmailConflict,
  CustomerEmailSchema,
  CustomerGroupIdSchema,
  CustomerGroupAssignmentInputSchema,
  CustomerGroupNotFound,
  CustomerGroupSchema,
  CustomerIdSchema,
  CustomerIdentifierSchema,
  CustomerInvalidIdentifier,
  CustomerMetadataSchema,
  CustomerNotFound,
  CustomerPaymentIdentitySchema,
  CustomerProfileSchema,
  CustomerRepositoryService,
  CustomerSerializedAddressIdSchema,
  CustomerSerializedGroupIdSchema,
  CustomerSerializedIdSchema,
  CustomerTrimmedStringSchema,
  LinkCustomerAuthInputSchema,
  ResolveCustomerFromAuthInputSchema,
  UpdateCustomerProfileInputSchema,
  createCustomerAddressId,
  createCustomerAddressIdEffect,
  createCustomerGroupId,
  createCustomerGroupIdEffect,
  createCustomerId,
  createCustomerIdEffect,
  serializeCustomerAddressId,
  serializeCustomerGroupId,
  serializeCustomerId,
  type CustomerExpectedError,
} from "./domain";
export type {
  CreateCustomerAddressInput,
  CreateCustomerGroupInput,
  CreateCustomerInput,
  CustomerAddress,
  CustomerAddressId,
  CustomerApiAddress,
  CustomerApiGroup,
  CustomerApiList,
  CustomerApiProfile,
  CustomerGroup,
  CustomerGroupAssignmentInput,
  CustomerGroupId,
  CustomerId,
  CustomerPaymentIdentity,
  CustomerProfile,
  CustomerRepository,
  LinkCustomerAuthInput,
  ResolveCustomerFromAuthInput,
  UpdateCustomerProfileInput,
} from "./domain";
export { customerExtensionPoints, customerModule } from "./module";
export { customerPermissionList, customerPermissions } from "./permissions";
export {
  InMemoryCustomerRepository,
  createInMemoryCustomerRepositoryLayer,
  createInMemoryCustomerRepository,
  createResettableInMemoryCustomerRepository,
  defaultCustomerRepository,
  type ResettableCustomerRepository,
} from "./repositories";
export {
  CUSTOMER_AUTH_LINKED_EVENT,
  CUSTOMER_CREATED_EVENT,
  CUSTOMER_UPDATED_EVENT,
  CustomerService,
  createCustomerRepositoryLayer,
  createCustomerServiceFromDependenciesLayer,
  createCustomerService,
  createCustomerServiceLayer,
  defaultCustomerService,
  type CreateCustomerServiceOptions,
  type CustomerAuthLinkedEventPayload,
  type CustomerChangedEventPayload,
  type CustomerServiceFailure,
  type CustomerServiceShape,
} from "./services";
export { createTestCustomerService } from "./testing";
