export {
  customerAddressCustomerIndexName,
  customerAddressTableName,
  customerAuthUserIndexName,
  customerEmailIndexName,
  customerGroupCustomerTableName,
  customerGroupHandleIndexName,
  customerGroupTableName,
  customerMigration,
  customerSchema,
  customerTableName,
  type CustomerAddressRow,
  type CustomerDatabase,
  type CustomerDatabaseSchema,
  type CustomerGroupRow,
  type CustomerInsert,
  type CustomerRow,
  type CustomerSchemaKey,
} from "@ecommerce/customer/schema";
