export {
  inventoryAdjustmentEventTableName,
  inventoryItemSkuIndexName,
  inventoryItemTableName,
  inventoryLevelScopeIndexName,
  inventoryLevelTableName,
  inventoryMigration,
  inventoryReservationIdempotencyIndexName,
  inventoryReservationLevelIndexName,
  inventoryReservationTableName,
  inventorySchema,
  stockLocationTableName,
  type InventoryAdjustmentEventInsert,
  type InventoryAdjustmentEventRow,
  type InventoryDatabase,
  type InventoryDatabaseSchema,
  type InventoryItemInsert,
  type InventoryItemRow,
  type InventoryLevelInsert,
  type InventoryLevelRow,
  type InventoryReservationInsert,
  type InventoryReservationRow,
  type InventorySchemaKey,
  type StockLocationInsert,
  type StockLocationRow,
} from "@ecommerce/inventory/schema";
