export {
  promotionCampaignTableName,
  promotionCodeIndexName,
  promotionMigration,
  promotionRedemptionPromotionIndexName,
  promotionRedemptionTableName,
  promotionRulePromotionIndexName,
  promotionRuleTableName,
  promotionSchema,
  promotionTableName,
  promotionUsageLimitPromotionIndexName,
  promotionUsageLimitTableName,
  type PromotionCampaignInsert,
  type PromotionCampaignRow,
  type PromotionDatabase,
  type PromotionDatabaseSchema,
  type PromotionInsert,
  type PromotionRedemptionInsert,
  type PromotionRedemptionRow,
  type PromotionRow,
  type PromotionRuleInsert,
  type PromotionRuleRow,
  type PromotionSchemaKey,
  type PromotionUsageLimitInsert,
  type PromotionUsageLimitRow,
} from "@ecommerce/promotion/schema";
